### ISSUE TITLE
Command --options don't work on CLI

### ISSUE THREAD

**Issue by jameswilson** [BluesparkLabs/spark#10]
I added a way to use command options for the `drupal:backup` command, and even documented it on issue #8 how these are in theory supposed to work.

However, for some reason the commands are not being picked up.

```
$ composer run spark drupal:backup --timeout=0 --keep="30 days"

[Symfony\Component\Console\Exception\RuntimeException]  
  The "--keep" option does not exist.   

```

**Comment by balintbrews** [comment]
This happens because `composer run-script` passes all arguments which start with `--` to `composer` itself, rather than to the script it runs. In order to have them passed to the script, we need to signify the end of the the Composer options with a double-dash.

The example command you posted should be issued the following way:

    $ composer run spark drupal:backup --timeout=0 -- --keep="30 days"

Obviously, this is not ideal for Spark. Even when we don't intend to pass anything to Composer, we'd need to use the double-dash when we use an argument. E.g.:

    $ composer run spark -- mysql:dump --non-sanitized

#36 is my proposal to overcome this.

I recommend that we take that approach and close this issue.

**Comment by jameswilson** [comment]
@balintk Agreed. closing this in favor of #36.
